
services:
  nginx_server:
    container_name: nginx_server
    image: nginx_server
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html/
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      dns_network:
        ipv4_address: 192.168.1.11

  dns_server:
    container_name: dns_server
    image: dns_server
    build:
      context: ./dns/
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named
    networks:
      dns_network:
        ipv4_address: 192.168.1.10
    dns:
      - 192.168.1.10

networks:
  dns_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

