
services:
  nginx:
    container_name: nginx_dns
    image: nginx_dns
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html/
      - ./nginx/conf.d:/etc/nginx/conf.d/

  dns:
    container_name: dns_c
    image: dns_i
    build:
      context: ./dns/
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/resolv.conf:/etc/resolv.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named

